### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by stuartarchibald** [RadeonOpenCompute/ROCm-CompilerSupport#2]
The COMGR API has functions to set and get logging state, and the `amd_comgr_data_kind_t` has a `AMD_COMGR_DATA_KIND_LOG` output kind. I've tried setting the logging state to "on" but it would appear that nothing is generated (tried with a few actions, `AMD_COMGR_ACTION_ASSEMBLE_SOURCE_TO_RELOCATABLE`, `AMD_COMGR_ACTION_LINK_RELOCATABLE_TO_RELOCATABLE`, `AMD_COMGR_ACTION_LINK_RELOCATABLE_TO_EXECUTABLE`) is this intended or are my assumptions over use incorrect? Thanks.

**Comment by scott-linder** [comment]
Hi, thank you for filing this! Your assumptions are correct, and the fact that this is not yet implemented should at least be in the API documentation. I am currently working on a patch to implement logging as described.

**Comment by stuartarchibald** [comment]
Great, thanks.

**Comment by scott-linder** [comment]
This is implemented in a6a19c199, with a few minor exceptions (e.g. the "X warnings generated." meta-diagnostics). Those exceptions cannot be fixed until https://reviews.llvm.org/D53768 is accepted upstream.
