### ISSUE TITLE
[comgr] LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by atamazov** [RadeonOpenCompute/ROCm-CompilerSupport#30]
When comgr is statically linked to the app, and app does NOT use HIP runtime, the app fails at exit:
```
user@machine:/dockerx/github/miopen01/build/debug.hip-clang# ./bin/test_bn_aux
: CommandLine Error: Option 'disassemble' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
user@machine:/dockerx/github/miopen01/build/debug.hip-clang# echo $?
134
```
Many MIOpen unit tests are affected, for example `test_bn_aux`. Ditto user applications that link MIOpen library.

The workaround is adding a call to `hipInit()` somewhere in the app.

**Comment by scott-linder** [comment]
What is `the app`? Can you include a reproducer (a link and some build instructions would save a lot of time).

To be clear, when you say the workaround is to call `hipInit()` does that also imply that the app must start to use the HIP runtime? I'm uncertain what you mean in the first line when you say "and the app does NOT use HIP runtime".

**Comment by atamazov** [comment]
> What is `the app`? Can you include a reproducer (a link and some build instructions would save a lot of time).

I suspect that `int main() {return 0;}` + statically linked amd_comgr.so (iirc) would work. Or you can build MIOpen and run tests (with hip-clang docker image 2272). Let me provide more detailed instructions when I have time. 

> To be clear, when you say the workaround is to call `hipInit()` does that also imply that the app must start to use the HIP runtime? 

No.

> I'm uncertain what you mean in the first line when you say "and the app does NOT use HIP runtime".

I mean app that does not use HIP runtime at all. I guess that runtime can be used only after initialization. This is the workaround that I use in miopen (and it works so far):
```C++
#if MIOPEN_WORKAROUND_ROCM_COMPILER_SUPPORT_ISSUE_30
namespace {
void toCallHipInit() __attribute__((constructor(1000)));
void toCallHipInit() { hipInit(0); }
} // namespace
#endif
```

**Comment by atamazov** [comment]
@scott-linder And, -- thanks for feedback, Scott.

**Comment by aserio** [comment]
@atamazov, @scott-linder, Would you be able to provide an update on this issue status?

**Comment by atamazov** [comment]
I have workaround and it seems that it works for now.

**Comment by atamazov** [comment]
The issue is not observed since ROCm 4.3.
