### ISSUE TITLE
Add documentatio/debug output for command line equivalent operations

### ISSUE THREAD

**Issue by stuartarchibald** [RadeonOpenCompute/ROCm-CompilerSupport#5]
Most of the `amd_comgr_action_kind_s`s have command line equivalent behaviours, it'd be useful to declare the command line tool wrapped and also the default flags being applied for each operation in the documentation/header file. Further perhaps dump the equivalent operation to stdout in debug mode? Thanks.

**Comment by lamb-j** [comment]
The current Comgr emits command-line equivalent options/flags for many of the available Actions to stdout using the following:
export AMD_COMGR_EMIT_VERBOSE_LOGS=1
export AMD_COMGR_REDIRECT_LOGS=stdout

Post here if there is any additional debug output we can add!
