### ISSUE TITLE
Is LLVM IR supported as a source language?

### ISSUE THREAD

**Issue by stuartarchibald** [RadeonOpenCompute/ROCm-CompilerSupport#7]
Seems like the `amd_comgr_language_t` enum has no entry for LLVM IR as a source language, I'm guessing an action of kind `AMD_COMGR_ACTION_COMPILE_SOURCE_TO_BC` fails due to this?

**Comment by scott-linder** [comment]
Currently no, there are no actions which accept LLVM IR. An action to convert LLVM IR to BC could be added if it is useful.

**Comment by lamb-j** [comment]
We still don't have an action to deal with LLVM IR directly. Instead we mostly deal with things at the bitcode level. Let me know if this is still needed and I can reopen this issue.
